export const BRAND_CONFIG = {
  name: "Dinning Zone",
  tagline: "Fresh food. Fast at your door.",
  deliveryRadiusKm: 5.0,
  supportPhone: "+91 98765 43210",
  colors: {
    primary: "#D94F30",
    primaryDark: "#B83B20",
    accent: "#F5A524",
    bg: "#FFF9F3",
    surface: "#FFFFFF",
    border: "#EFE6DC",
    text: "#1F1F1F",
    muted: "#6B6B6B",
    success: "#2E9E5B",
    warning: "#F5A524",
    error: "#D92D20",
    info: "#2F6FED",
  },
  logos: {
    main: "/brand/logo.png",
    white: "/brand/logo-white.png",
    icon: "/brand/icon-192.png",
    favicon: "/brand/favicon.ico.png",
    pattern: "/brand/pattern.png",
  },
  banners: {
    hero: "/banners/hero.webp",
    welcome: "/banners/welcome.webp",
    home: "/banners/banner-home.webp",
    biryani: "/banners/banner-biriyani.webp",
    coupons: "/banners/banner-coupens.webp",
    freeDelivery: "/banners/banner-free-delivery.webp",
    pizzaBurger: "/banners/banner-pizza-burger.webp",
    dessertDrink: "/banners/banner-dessert-drink.webp",
    cartImg: "/banners/cart-img.png",
    closeShopImg: "/banners/close-shop-img.png",
    mapImg: "/banners/map-img.png",
    riderImg: "/banners/raider-img.png",
  },
} as const;
